Repository kiegroup/rhpam-kogito-operator, pull requests merged in 2021-06, with the labels that each got.

#42 [KOGITO-5175] - Changes for productized build of Operator bundle
  Jenkinsfile
  Makefile
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/bump-version.sh.bats
  hack/update-bundle.sh
  image-bundle.yaml
  rhpam-kogito-operator.yaml
  test/pkg/installers/rhpam_kogito_installer.go
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#43 [KOGITO-5272] Update operator image name in sync job
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.upstream-operator-sync
Labels: needs review :mag:

#45 [RHPAM-3725] - Missing RHPAM Kogito operator description in OperatorH…
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:

#46 [RHPAM-3725]- [1.5.x] - Missing RHPAM Kogito operator description in …
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: ready :rocket:

#47 Upgrade bundle version to rhpam-kogito-operator.v7.11.0-1
  Makefile
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:
