Repository kiegroup/rhpam-kogito-operator, pull requests merged in 2021-07, with the labels that each got.

#50 [KOGITO-5460] Change com.redhat.openshift.versions [1.5.x]
  image-bundle.yaml
Labels: needs review :mag:

#51 [KOGITO-5460] Change com.redhat.openshift.versions
  image-bundle.yaml
Labels: ready :rocket:

#49 [1.5.x] [RHPAM-3681] Add metering labels for Kogito pods
  RELEASE_NOTES.md
  controllers/kogitobuild_controller.go
  controllers/runtime_deployer.go
  go.mod
  go.sum
  internal/kogitobuild.go
  internal/labels.go
Labels: operator :cloud:, ready :rocket:

#48 [RHPAM-3681] Add metering labels for Kogito resources
  controllers/kogitobuild_controller.go
  controllers/runtime_deployer.go
  go.mod
  go.sum
  internal/kogitobuild.go
  internal/labels.go
Labels: operator :cloud:, ready :rocket:

#52 [KIECLOUD-547] - Prepare RHPAM Kogito Operator for 7.11.1 release
  Makefile
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  example/quarkus-jvm.Dockerfile
  example/springboot.Dockerfile
  image-bundle.yaml
  image-prod.yaml
  image.yaml
  modules/org.kie.kogito.builder/module.yaml
  modules/org.kie.kogito.bundleinstall/module.yaml
  modules/org.kie.kogito.gomoddownloader/module.yaml
  rhpam-kogito-operator.yaml
  version/version.go
Labels: operator :cloud:, ready :rocket:

#53 KOGITO-5480 Reorganized seed jobs & trigger automatically
  .jenkins/dsl/Jenkinsfile.seed
Labels: needs review :mag:

#55 [1.5.x] KOGITO-5480 Reorganized seed jobs & trigger automatically (#53)
  .jenkins/dsl/Jenkinsfile.seed
Labels: cherry-pick :cherries:, ready :rocket:

#57 Update to replaces and reference initial 7.11.0 build
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
Labels: needs review :mag:

#56 [KOGITO-5326] Setup deploy/promote notifications on demand
  Jenkinsfile.upstream-operator-sync
Labels: needs review :mag:

#44 BXMSPROD-1265: Conscious language initiative
  .github/bot-files/comments.yml
  .github/pull_request_template.md
  .github/workflows/jenkins-tests-PR.yml
  .jenkins/dsl/test.sh
  Makefile
  RELEASE_NOTES.md
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  example/springboot.yaml
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#59 [KOGITO-5205] - ImageStream tag is not updated when image parameter i…
  controllers/kogitoruntime_controller.go
  controllers/kogitoruntime_finalizer.go
Labels: cherry-pick :cherries:, operator :cloud:, ready :rocket:

#61 KOGITO-4470 - cherrypick - ConfigMap required ownerReference as contr…
  controllers/kogitoruntime_controller.go
  go.mod
  go.sum
  test/pkg/installers/rhpam_kogito_installer.go
Labels: bdd-tests 🧪, cherry-pick :cherries:, needs review :mag:, operator :cloud:
