Repository kiegroup/rhpam-kogito-operator, pull requests merged in 2021-05, with the labels that each got.

#26 [KOGITO-5005] - Operator print irrelevant metadata in logs
  controllers/kogitobuild_controller.go
  controllers/kogitoruntime_controller.go
  controllers/runtime_deployer.go
  go.mod
  go.sum
  internal/kogitobuild.go
  internal/kogitoruntime.go
Labels: operator :cloud:

#27 [KOGITO-4898] Set probe defaults based on YAML action values
  controllers/kogitoruntime_controller.go
  go.mod
  go.sum
Labels: needs review :mag:, operator :cloud:

#28 [KOGITO-5063] BDD tests: Support using builder images from insecure registry
  go.mod
  go.sum
  test/pkg/framework/kogitobuild.go
  test/pkg/steps/deploy_files.go
  test/pkg/steps/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#29 [1.5.x][KOGITO-5063] BDD tests: Support using builder images from insecure r…
  go.mod
  go.sum
  test/framework/kogitobuild.go
  test/steps/deploy_files.go
  test/steps/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#33 [KOGITO-5100] BDD tests: Allow using example repository with invalid …
  test/pkg/steps/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#34 [1.5.x][KOGITO-5100] BDD tests: Allow using example repository with invalid …
  test/steps/kogitobuild.go
Labels: bdd-tests 🧪, needs review :mag:

#31 [1.5.x][BXMSPROD-1306] Update to include micro in the version.
  image-bundle.yaml
  image-prod.yaml
  image.yaml
  modules/org.kie.kogito.builder/module.yaml
  modules/org.kie.kogito.bundleinstall/module.yaml
  modules/org.kie.kogito.gomoddownloader/module.yaml
Labels: cherry-pick :cherries:, ready :rocket:

#35 [KOGITO-5104] - [1.5.x] - RHPAM Kogito operator creates wrong default image tags
  RELEASE_NOTES.md
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitoruntime_controller.go
  go.mod
  go.sum
  hack/ci/ensure-image.sh
  hack/ci/olm-pretest.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  rhpam-kogito-operator.yaml
Labels: needs review :mag:, on hold :hand:, operator :cloud:

#36 [KOGITO-5104] - RHPAM Kogito operator creates wrong default image tags
  RELEASE_NOTES.md
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/kogitobuild_controller.go
  controllers/kogitoruntime_controller.go
  go.mod
  go.sum
  hack/ci/ensure-image.sh
  hack/ci/olm-pretest.sh
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  rhpam-kogito-operator.yaml
Labels: needs review :mag:, operator :cloud:

#38 BDD tests: Use upstream images for builds as a temporary workaround
  Jenkinsfile
  Jenkinsfile.upstream-operator-sync
Labels: CI/CD :loop:, needs review :mag:

#40 [KOGITO-5175] - [1.5.x] - Changes for productized build of Operator bundle
  Jenkinsfile
  Makefile
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  go.sum
  hack/bump-version.sh.bats
  hack/update-bundle.sh
  image-bundle.yaml
  rhpam-kogito-operator.yaml
  test/installers/rhpam_kogito_installer.go
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:
