Repository kiegroup/rhpam-kogito-operator, pull requests merged in 2021-04, with the labels that each got.

#17 Updating bot reviewers.yml
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#13 [KOGITO-4858] Automatic build of examples
  Jenkinsfile
  Makefile
  go.mod
  go.sum
  hack/run-tests.sh
  meta/meta.go
  test/Makefile
  test/main_test.go
  test/pkg/framework/kogitobuild.go
  test/pkg/framework/kogitoruntime.go
  test/pkg/installers/rhpam_kogito_installer.go
  test/pkg/steps/data.go
  test/pkg/steps/deploy_files.go
  test/pkg/steps/kogitobuild.go
  test/pkg/steps/kogitoruntime.go
  test/pkg/steps/mappers/create_kogito_build.go
  test/pkg/steps/openshift.go
  test/pkg/steps/operator.go
Labels: CI/CD :loop:, bdd-tests 🧪, needs review :mag:

#15 [KOGITO-4888] Update Prometheus operator GitHub link
  controllers/runtime_deployer.go
  go.mod
  go.sum
  meta/meta.go
Labels: needs review :mag:, operator :cloud:

#12 [KOGITO-4322] Add startup probes to API
  Makefile
  api/v1/probe.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/bases/rhpam.kiegroup.org_kogitoruntimes.yaml
  go.mod
  go.sum
  rhpam-kogito-operator.yaml
Labels: operator :cloud:

#18 [KOGITO-4946] Registering correct k8s objects
  Makefile
  go.sum
  hack/run-tests.sh
  hack/tests-clean-files.sh
  hack/tests-download-files.sh
  test/main_test.go
  test/pkg/steps/data.go
Labels: bdd-tests 🧪, needs review :mag:, operator :cloud:

#21 KOGITO-4851 Prod changes to build in OSBS
  README.md
  image-prod.yaml
  modules/org.kie.kogito.builder/install.sh
Labels: ready :rocket:

#20 KOGITO-4851 Prod changes to build in OSBS [1.5.x]
  README.md
  image-prod.yaml
  modules/org.kie.kogito.builder/install.sh
Labels: ready :rocket:

#19 [KOGITO-4952] Support installing product operator using insecure regi…
  test/pkg/installers/rhpam_kogito_installer.go
Labels: bdd-tests 🧪, needs review :mag:

#24 [1.5.x] Use 1.5 images and examples for tests
  test/.default_config
Labels: bdd-tests 🧪, needs review :mag:

#22 [KOGITO-4846] Create a nightly job to update go.mod file and run BDD …
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.upstream-operator-sync
Labels: CI/CD :loop:, needs review :mag:

#23 [1.5.x][KOGITO-4952] Support installing product operator using insecure regi…
  go.mod
  go.sum
  test/installers/rhpam_kogito_installer.go
Labels: bdd-tests 🧪, ready :rocket:
