Repository kiegroup/rhpam-kogito-operator, pull requests merged in 2021-08, with the labels that each got.

#62 Correct olm tests
  hack/ci/operator-ensure-manifests.sh
  hack/ci/run-olm-tests.sh
  hack/env.sh
Labels: ready :rocket:

#54 RHPAM-3777 Allow to update prod version
  .github/workflows/Kogito-Operator-PR-Check.yaml
  .jenkins/dsl/jobs.groovy
  Jenkinsfile.update-prod-version
  hack/bump-version.sh
  hack/bump-version.sh.bats
  hack/env.sh
Labels: ready :rocket:

#60 Add KogitoInfra capablities in RHPAM Kogito Operator
  PROJECT
  api/v1/kogitoinfra_types.go
  api/v1/kogitoruntime_types.go
  api/v1/kogitoservices.go
  api/v1/zz_generated.deepcopy.go
  api/v1/zz_generated.openapi.go
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  bundle/manifests/rhpam.kiegroup.org_kogitoinfras.yaml
  bundle/manifests/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/bases/rhpam.kiegroup.org_kogitoinfras.yaml
  config/crd/bases/rhpam.kiegroup.org_kogitoruntimes.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_kogitoinfras.yaml
  config/crd/patches/webhook_in_kogitoinfras.yaml
  config/manifests/bases/rhpam-kogito-operator.clusterserviceversion.yaml
  config/rbac/kogitoinfra_editor_role.yaml
  config/rbac/kogitoinfra_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/rhpam_v1_kogitoinfra.yaml
  controllers/kogitoinfra_controller.go
  controllers/kogitoruntime_controller.go
  controllers/kogitoruntime_finalizer.go
  controllers/suite_test.go
  example/process-quarkus-example-persistence.yaml
  go.mod
  go.sum
  internal/kogitoinfra.go
  main.go
  rhpam-kogito-operator.yaml
Labels: operator :cloud:, bdd-tests 🧪, ready :rocket:

#64 Fix build problem with addlicense library
  go.tools.mod
  go.tools.sum
  hack/addheaders.sh
Labels: ready :rocket:, release-7.12.0

#63 KOGITO-5685 RHPAM BDD tests with events
  Makefile
  api/v1/kogitoinfra_types.go
  bundle/manifests/rhpam-kogito-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/kogitoinfra_controller.go
  go.mod
  go.sum
  hack/tests-clean-files.sh
  hack/tests-download-files.sh
  rhpam-kogito-operator.yaml
  test/pkg/framework/kogitoinfra.go
  test/pkg/steps/data.go
  test/pkg/steps/kogitoinfra.go
Labels: operator :cloud:, bdd-tests 🧪, ready :rocket:

#66 BDD: Removed usage of Maven mirror
  Jenkinsfile.upstream-operator-sync
Labels: needs review :mag:

#67 KOGITO-5742 BDD: Setup amq streams to 1.8.x
  Makefile
  go.mod
  go.sum
  hack/update-dependencies.sh
  test/pkg/installers/amqstreams_installer.go
Labels: needs review :mag:, bdd-tests 🧪

#69 KOGITO-4113 Move all jenkins files to .ci/jenkins
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/Jenkinsfile.update-prod-version
  .ci/jenkins/Jenkinsfile.upstream-operator-sync
  .ci/jenkins/dsl/Jenkinsfile.seed
  .ci/jenkins/dsl/jobs.groovy
  .ci/jenkins/dsl/test.sh
  .github/workflows/jenkins-tests-PR.yml
Labels: needs review :mag:
